"""me quedo con una sede

Revision ID: 6f70adec502b
Revises: cab0eb985ee7
Create Date: 2022-10-01 14:13:57.895191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f70adec502b'
down_revision = 'cab0eb985ee7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elemento', 'sede2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elemento', sa.Column('sede2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
