"""ver cambios de db

Revision ID: cab0eb985ee7
Revises: 8cd81d92f3ee
Create Date: 2022-10-01 14:13:10.355729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab0eb985ee7'
down_revision = '8cd81d92f3ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elemento', sa.Column('sede', sa.String(), nullable=True))
    op.add_column('elemento', sa.Column('sede2', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('sede', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'sede')
    op.drop_column('elemento', 'sede2')
    op.drop_column('elemento', 'sede')
    # ### end Alembic commands ###
