"""setting up now

Revision ID: d4f3b660fba6
Revises: 728d9de0489b
Create Date: 2022-09-29 17:35:44.045963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f3b660fba6'
down_revision = '728d9de0489b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
